travis:
  secure:
    BINSTAR_TOKEN: 2KfJvQrBVjUMBeFJXH6AdE+9Jvhe6FDZ84OFgsTQ0siSDTUUkm8Cct6TWBSMY7wa8IV6UF0kpGOl9JWbUv6aXmtuqGrM4AjtwN4SGdSAX3YrJ6RlXAkUV+e91/JMEMv8hRG0YhrJWQA520qe3Q+u+CKJiTDxczemHAt0NMeeGTxpq24DVOdZT3Al3beB/oA983qAHERPq0+wc5SWJslSbhQJmV+YJu4zK7CjoqHVLs3loQSp6mtAI5zyv19a7z2vqSrI99ckVRF4+I/JvK+lt0t14NLKDxnZznURsBUFmCOwAQn4SrPTE13G2hzqtyMM6z0STzX0UBCir+2t8p4ZpHmXnueu7ox5v4JBjISPhiY94dDn1BU10trKWRW0ACnuFnTke6QrV8+kgGQLza80OE/L6X8slI1v0LdyttS09OAJ2TaB1vZsIA9Hii4qB7yqEOxrzFvCk6hvkcUv0UIbZRShzkL1ImS6W5E2i4mRQNh6K+d8SHJRL9qSZGfHAtgmQMiyUn+hL8/q+4j1QNEG8AKIH7Inbc1j9eilv0NXzXZh9DowdwD+TO2L9kCtN/T658RN6V3NdknmPN0w+yP8bCQ1UT7pKFxpcMXlv96czakhYMcxO5oWcdKN6GmDcBL31fUK71vNp2RY49ebA/kyzFQ1IIq4WQ/BLUPw3kUFmCE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
