appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: XwKi1n4/G4IZAas1qRs08ZeI/KXuamE5YsR12ejBPhpVJhbLfWH31vsh1CDXA7GCPJx/iub7Mdmh71Ns3Beglk1ILByXtVeNpiyLzxmCuq+7VKaABMUYtt1RM42v/mk3F6LxMlmqGhP2OJdykfNTtS6EYtVEY4JtksBvgEh3QvoxilHtNd+XS/UMWLG9nau0AgxbTzjVr1YfLrgjKtH+n3oicqFVjYdlxcNh62NmGUb7OzpZcNMuNYkryScbf1wkoHNgLbSJWZxoo+wOdzZUP+rEVYqFuh17s0QB/N+oeiE8+4a4VcyXcHUllaY7WHU5dZtUlmFzNzwKWXR2DsgLvlzaiJpDeOGgK4YYqixjlQHyuStFnkZ1xa6PpiwIOY4EX2ZQLTKvqu2sjznYU5KGb29WyWatILgQbTFVlDR7eCC+gEJv5YOMYeJ3sOMTK7Q0TXw5qcVxsotDdLBlyL+DN6Tr+WokSdXCGL2jP1LrdxVmd0UF4hU3zMcFi2Ag60vYt4JjNKdalGMpBVT/I7yT+e6jzH/6fu1haOt32isc4Xmo/6AbcoKDOHXGH+Vq7vRBb6k3q1JHTtW1uIxyPezVHR+FkZ7/u9YlC6xBi6dgZ02vzO0x3DZuNy3FPWMGY8YgsYHfol396mlpBeQhJTgIUhwqGrUKTd4qx2Ljogo5SRs=}
